[alias]
lint = [
    "clippy",
    "--workspace",
    "--message-format=json",
    "--all-targets",
    "--",
    "-D",
    "clippy::cargo",
    "-D",
    "clippy::complexity",
    "-D",
    "clippy::correctness",
    "-D",
    "clippy::pedantic",
    "-D",
    "clippy::perf",
    "-D",
    "clippy::restriction",
    "-D",
    "clippy::style",
    "-D",
    "clippy::suspicious",
    "-A",
    "clippy::implicit_return",
]
