[alias]
lint = [
    "clippy",
    "--workspace",
    "--message-format=json",
    "--all-targets",
    "--",
    "-D",
    "clippy::cargo",
    "-D",
    "clippy::complexity",
    "-D",
    "clippy::correctness",
    "-D",
    "clippy::pedantic",
    "-D",
    "clippy::perf",
    "-D",
    "clippy::restriction",
    "-D",
    "clippy::style",
    "-D",
    "clippy::suspicious",
    "-A",
    "clippy::implicit_return",
    "-A",
    "clippy::shadow_unrelated",
    "-A",
    "clippy::shadow-reuse",
    "-A",
    "clippy::used_underscore_binding",
    "-A",
    "clippy::separated_literal_suffix",
    "-A",
    "clippy::integer_arithmetic",
    "-A",
    "clippy::self_named_module_files",
    "-A",
    "clippy::single-char-lifetime-names",
    "-A",
    "clippy::multiple_crate_versions",
]
