[target.'cfg(all())']
rustflags = [
    "-Dclippy::cargo",
    "-Dclippy::complexity",
    "-Dclippy::correctness",
    "-Dclippy::pedantic",
    "-Dclippy::perf",
    "-Dclippy::restriction",
    "-Dclippy::style",
    "-Dclippy::suspicious",
    "-Dfuture_incompatible",
    "-Dnonstandard-style",
    "-Dunsafe_code",
    # Exceptions
    "-Aclippy::float_arithmetic",
    "-Aclippy::implicit_return",
    "-Aclippy::integer_arithmetic",
    "-Aclippy::multiple_crate_versions",
    "-Aclippy::self_named_module_files",
    "-Aclippy::separated_literal_suffix",
    "-Aclippy::shadow-reuse",
    "-Aclippy::shadow_unrelated",
    "-Aclippy::single-char-lifetime-names",
    "-Aclippy::used_underscore_binding",
]
